In [1]:
import tensorflow as tf
import numpy as np

In [7]:
#list:high cost for images storage
#numpy.array
#tensorflow.tensor:born for machine learning
a = tf.constant(1)
b = tf.constant(1.)
c = tf.constant([True, False])
d = tf.constant('hello nick')
print(a)
print(b)
print(c)
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([ True False], shape=(2,), dtype=bool)
tf.Tensor(b'hello nick', shape=(), dtype=string)


In [49]:
#some properties
x = [i for i in range(6)]
y = [i**2 for i in range(6)]
a = tf.constant([[1,2,3.5,4.5,False,True],x,y])

print(a.device)
print(a)
print(a.numpy()) #check data part(transfer to numpy array)
print(a.shape)
print(a.ndim)
print(a.dtype)

/job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[ 1.   2.   3.5  4.5  0.   1. ]
 [ 0.   1.   2.   3.   4.   5. ]
 [ 0.   1.   4.   9.  16.  25. ]], shape=(3, 6), dtype=float32)
[[ 1.   2.   3.5  4.5  0.   1. ]
 [ 0.   1.   2.   3.   4.   5. ]
 [ 0.   1.   4.   9.  16.  25. ]]
(3, 6)
2
<dtype: 'float32'>


In [59]:
#data type judgement
x = [i for i in range(6)]
y = [i**2 for i in range(6)]
a = tf.constant([[1,2,3.5,4.5,False,True],x,y])

#isinstance(*,tf.Tensor)
print(isinstance(a,tf.Tensor))
print(isinstance(x,tf.Tensor))
#tf.is_tensor()
print(tf.is_tensor(a))
print(tf.is_tensor(x))

True
False
True
False


In [112]:
#data type conversion
#tf.convert_to_tensor(*,dtype=*)
lta = [(i**2)/3 for i in range(6)]
npa = np.arange(6)
ltTOts = tf.convert_to_tensor(lta,dtype = tf.float32)
npTOts = tf.convert_to_tensor(npa,dtype=tf.int32)
print("lta:{0}".format(lta))
print(ltTOts)
print("****************")
print("npa:{0}".format(npa))
print(npTOts)

#dtype conversion between tensors
print("****************")
dtypeConvsTf = tf.cast(ltTOts,dtype=tf.int32)
print("lta:{0}".format(lta))
print("dtype conversion between tensors:",end="")
print(dtypeConvsTf)



lta:[0.0, 0.3333333333333333, 1.3333333333333333, 3.0, 5.333333333333333, 8.333333333333334]
tf.Tensor([0.         0.33333334 1.3333334  3.         5.3333335  8.333333  ], shape=(6,), dtype=float32)
****************
npa:[0 1 2 3 4 5]
tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
****************
lta:[0.0, 0.3333333333333333, 1.3333333333333333, 3.0, 5.333333333333333, 8.333333333333334]
dtype conversion between tensors:tf.Tensor([0 0 1 3 5 8], shape=(6,), dtype=int32)


In [110]:
#create tensor with differential structures : tf.Variable()
a = tf.range(5)
#tf.Variable() gives a tensor differential structure 
b = tf.Variable(a)

print(b)
print(isinstance(b,tf.Tensor)) #False
print(isinstance(b,tf.Variable)) #True
print(tf.is_tensor(b)) #True correct answer
print(b.name) #Variable:0

#assign name while creating variables
print("****************")
c = tf.Variable(a,name="input_data_popoEmperor")
print(c.name)       #simple tensors do not have this attribute
print(c.trainable) #simple tensors do not have this attribute

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>
False
True
True
Variable:0
****************
input_data_popoEmperor:0
True


In [126]:
#tensor-numpy conversion
a = tf.range(5)
b = a.numpy()
print(a)
print(b)

print("****************")
a = tf.ones(1)
b = tf.ones([]) #scalar
print(a.numpy())
print(b.numpy())

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
[0 1 2 3 4]
****************
[1.]
1.0
